package com.labs64.netlicensing.domain.vo

enum class TransactionSource {

    SHOP,

    AUTO_LICENSE_CREATE,

    AUTO_LICENSE_UPDATE,

    AUTO_LICENSE_DELETE,

    AUTO_LICENSEE_CREATE,

    AUTO_LICENSEE_DELETE,

    AUTO_LICENSETEMPLATE_DELETE,

    AUTO_PRODUCTMODULE_DELETE,

    AUTO_PRODUCT_DELETE,

    AUTO_LICENSES_TRANSFER,

    SUBSCRIPTION_UPDATE,

    CANCEL_RECURRING_PAYMENT;
}